gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 jours
    ttl_update: true
    user_provider: app_user_provider
    token_parameter_name: refresh_token
    single_use: false
