# Routes pour les contrôleurs 
controllers:
    resource: ../src/Controller/
    type: attribute

# Specifics roads for the API
api:
    resource: ../src/Controller/
    type: attribute
    prefix: /api

# Specifics roads for the frontend
frontend:
    path: /{reactRouting}
    controller: App\Controller\FrontendController::index
    requirements:
        reactRouting: '^(?!api).*'
    defaults: {}
        